modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "immersiveoverlays"
version = "${version}"
displayName = "Immersive Overlays"
authors = "cassiancc, noelledotjpg"
description = '''
Overlays useful info like coordinates and the time - as long as you have the right item.
'''
logoFile = "assets/immersiveoverlays/icon.png"
issueTrackerURL = "https://github.com/cassiancc/Immersive-Overlays/issues"
displayURL="https://modrinth.com/mod/immersive-overlays"
modURL="https://modrinth.com/mod/immersive-overlays"
credits = "Additional sprites from ProbablyEkho, Crabbarition, Kelpiesaurus, and KevBo"

[[dependencies.immersiveoverlays]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.immersiveoverlays]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "immersiveoverlays.mixins.json"
